version: "2"
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/org/project)
        - blank
        - dot
        - alias
        - localmodule
      no-inline-comments: true
      no-prefix-comments: true
      custom-order: true
      no-lex-order: true
  exclusions:
    warn-unused: true
    generated: strict
  gofmt:
    simplify: true
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
      - pattern: 'a[b:len(a)]'
        replacement: 'a[b:]'
      - pattern: 'map[string]interface{}'
        replacement: 'map[string]any'
      - pattern: '[]interface{}'
        replacement: '[]any'

  goimports:
    local-prefixes:
      - github.com/org/project

  golines:
    max-len: 100
    tab-len: 2
    shorten-comments: true
    reformat-tags: true
    chain-split-dots: true
    ignore-generated: true
    force-multi-imports: false
    align-multiline-assign: true
    align-multiline-call: true
    align-multiline-struct: true