services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      #PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data         
      - ./migrations:/docker-entrypoint-initdb.d/
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    networks:
      - log_shelter_network
    command: [
      "postgres", 
      "-c", "config_file=/etc/postgresql/postgresql.conf"
    ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - log_shelter_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  nats:
    image: nats:2.10-alpine
    restart: unless-stopped
    command: ["-c", "/etc/nats/nats.conf"]
    volumes:
      - ./config/nats.conf:/etc/nats/nats.conf:ro
      - nats_data:/var/lib/nats/jetstream
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - log_shelter_network
    healthcheck:
      test: ["CMD", "nats", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  debezium:
    image: quay.io/debezium/server:2.5.0.Final
    ports:
      - "8080:8080"
    volumes:
      - ./config/debezium.properties:/debezium/conf/application.properties
    depends_on:
      - nats
      - postgres
      - elasticsearch
    networks:
      - log_shelter_network

  elasticsearch:
    image: elasticsearch:8.18.8
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - log_shelter_network

volumes:
  postgres_data:
  nats_data:
  redis_data:
  es_data:

networks:
  log_shelter_network:
    driver: bridge
    external: true