[logger]
developer_mode=true
[postgres]
host="localhost"
port=5432
username="postgres"
password="postgres"
database="postgres"
driver="pgx"
[nats]
url="nats://localhost:4222"
username="nats"
password="nats"