[logger]
developer_mode=true
[postgres]
host="localhost"
port=5432
username="postgres"
password="postgres"
database="postgres"
driver="pgx"
[nats]
url="nats://localhost:4222"
username="nats"
password="nats"
[telegram]
enabled=false
api_key="YOUR_TOKEN_HERE"
notificate_to=[758647978]
levels=["CRITICAL"]
[logs]
retencion_policy="after_time"
delete_after="5m"
cycle_time="2m"
